### ISSUE TITLE
Statement Validation

### ISSUE THREAD

**Issue by FeLungs** [FeLungs/xapi-profiles#8]
**Change Log Item Ids**

s22, s24, s25

**1.0.3 text -> 9274.1.1 Update**

The LRS SHOULD* return the Timestamp in UTC timezone.
->
An LRS shall convert Timestamps to UTC rather than rejecting Statements that send Timestamps not in UTC form

When comparing Durations, any precision beyond 0.01 second precision SHOULD* NOT be included in the comparison
->
When comparing Durations (or Statements containing them), any precision beyond 0.01 second precision shall not be included in the comparison.

When comparing Durations, any precision beyond 0.01 second precision SHOULD* NOT be included in the comparison
->
When comparing Durations (or Statements containing them), any precision beyond 0.01 second precision shall not be included in the comparison.

**Updates to xAPI Profile spec**

- Statement Template Rule section updated to include language saying rule any/all/none values should conform to xAPI requirements
- Statement Template Rule section updated to include language describing comparison between matchable values and xAPI data

**Comment by imartinezortiz** [comment]
This issue has been migrated to upstream repo https://github.com/adlnet/xapi-profiles/issues/268
